# Generated by Django 4.1.5 on 2023-01-31 20:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=datetime.datetime(2023, 1, 31, 23, 48, 44, 508245), verbose_name='Дата и время последней попытки')),
                ('status_attempt', models.CharField(default='runner', max_length=10, verbose_name='Статус попытки')),
                ('answer', models.CharField(default=200, max_length=250, verbose_name='Ответ почтового сервера')),
                ('mailing_id', models.IntegerField(null=True, verbose_name='Id рассылки')),
            ],
            options={
                'verbose_name': 'Попытка ',
                'verbose_name_plural': 'Попытки',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Емейл адрес')),
                ('full_name', models.CharField(max_length=250, verbose_name='Полное имя')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='MailingToClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing', models.IntegerField(verbose_name='ID рассылки')),
                ('client', models.IntegerField(verbose_name='ID Клиента')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Тема письма')),
                ('content', models.TextField(verbose_name='Содержание письма')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_mailing_start', models.TimeField(default=datetime.datetime(2023, 1, 31, 23, 48, 44, 507244), null=True, verbose_name='Время начала рассылки')),
                ('time_mailing_end', models.TimeField(default=datetime.datetime(2023, 1, 31, 23, 48, 44, 507244), null=True, verbose_name='Время окончания рассылки')),
                ('period_mailing', models.CharField(choices=[('one_day', 'раз в день'), ('one_week', 'раз в неделю'), ('one_month', 'раз в месяц')], default='one_week', max_length=50, verbose_name='Периодичность рассылки')),
                ('status', models.CharField(choices=[('create', 'создана'), ('runner', 'запущена'), ('ended', 'завершена')], default='create', max_length=100, verbose_name='Статус рассылки')),
                ('id_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='message_app.message', verbose_name='Выбрать письмо для рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
