# Generated by Django 4.1.5 on 2023-01-31 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0002_attempt_date_mailing_alter_attempt_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='date_mailing',
        ),
        migrations.AlterField(
            model_name='attempt',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 1, 48, 27, 999035), verbose_name='Дата и время последней попытки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='time_mailing_end',
            field=models.TimeField(default=datetime.datetime(2023, 2, 1, 1, 48, 27, 998035), null=True, verbose_name='Время окончания рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='time_mailing_start',
            field=models.TimeField(default=datetime.datetime(2023, 2, 1, 1, 48, 27, 998035), null=True, verbose_name='Время начала рассылки'),
        ),
    ]
